### ISSUE TITLE
errors/warnings in prepare.log and mikado_pick.log

### ISSUE THREAD

**Issue by jfouret** [lucventurini/mikado#112]
Hi ,

Many thanks for providing the community with mikado software,

I have tested this with the daijin pipeline. All was fine until the mikado prepare steps where I got some warnings in the prepare.log file. I have also noticed errors/warnings reported in the mikado pick log file. At the end I still got a results. Could you clarify those errors adn warnings to me ?

Here is how daijin pipeline has been configured.

```
daijin configure \
--scheduler "SLURM" \
--cluster_config cluster.yaml \
--scoring human.yaml \
--copy-scoring scoring.yaml \
--use-diamond \
-m permissive \
--flank 500 -i 50 26000 \
--threads 16 \
--genome /export/data/dbgit/ncbi/genomes/bats/pteVam.fa \
-al hisat \
-as cufflinks stringtie class \
-od OutPut \
--name Pvampyrus \
-o daijin.yaml \
--prot-db /export/data/dbgit/uniprot/mammals/mammals_reviewed.fa \
-r1 $(cut -f 1 sample_sheet_pe.tsv | xargs) \
-r2 $(cut -f 2 sample_sheet_pe.tsv | xargs) \
-s $(cut -f 3 sample_sheet_pe.tsv | xargs)
```

- Here is the assembly stats file after `daijin assemble`
> File genes monoexonic_genes transcripts transcripts_per_gene transcript_len_mean monoexonic_transcripts exons exons_per_transcript exon_len_mean
> class-0-hisat-CONDITION_1-0.gtf.stats 33295.0 6104.0 45731.0 1.35 1426.37 6104.0 259719.0 5.68 251.15
> class-0-hisat-CONDITION_2-0.gtf.stats 31880.0 5978.0 42851.0 1.32 1351.98 5978.0 243340.0 5.68 238.08
> class-0-hisat-CONDITION_3-0.gtf.stats 5606.0 4984.0 5655.0 1.01 640.69 4984.0 8765.0 1.55 413.36
> class-0-hisat-CONDITION_4-0.gtf.stats 41781.0 7618.0 60019.0 1.41 1762.75 7618.0 331632.0 5.53 319.02
> class-0-hisat-CONDITION_5-0.gtf.stats 41726.0 7098.0 59397.0 1.39 1769.16 7098.0 324650.0 5.47 323.68
> class-0-hisat-CONDITION_6-0.gtf.stats 34440.0 5680.0 47809.0 1.36 1661.91 5680.0 270419.0 5.66 293.82
> cufflinks-0-hisat-CONDITION_1-0.gtf.stats 35040.0 15967.0 44288.0 1.26 1944.94 16062.0 225295.0 5.09 382.33
> cufflinks-0-hisat-CONDITION_2-0.gtf.stats 30277.0 12114.0 39071.0 1.29 1887.1 12159.0 218598.0 5.59 337.29
> cufflinks-0-hisat-CONDITION_3-0.gtf.stats 56710.0 34506.0 65359.0 1.15 1223.76 34582.0 212474.0 3.25 376.44
> cufflinks-0-hisat-CONDITION_4-0.gtf.stats 51900.0 30345.0 63568.0 1.22 2393.49 30861.0 250781.0 3.95 606.7
> cufflinks-0-hisat-CONDITION_5-0.gtf.stats 55632.0 34149.0 67873.0 1.22 2511.55 34821.0 257293.0 3.79 662.54
> cufflinks-0-hisat-CONDITION_6-0.gtf.stats 41654.0 22672.0 52353.0 1.26 2340.48 23023.0 225819.0 4.31 542.61
> stringtie-0-hisat-CONDITION_1-0.gtf.stats 42900.0 21934.0 61470.0 1.42 2009.91 22583.0 310991.0 5.06 397.28
> stringtie-0-hisat-CONDITION_2-0.gtf.stats 36470.0 16652.0 52429.0 1.43 1914.35 17128.0 284788.0 5.43 352.43
> stringtie-0-hisat-CONDITION_3-0.gtf.stats 63401.0 42114.0 79601.0 1.25 1343.7 42586.0 290008.0 3.64 368.82
> stringtie-0-hisat-CONDITION_4-0.gtf.stats 63937.0 40657.0 89209.0 1.39 2531.28 41831.0 384702.0 4.31 586.98
> stringtie-0-hisat-CONDITION_5-0.gtf.stats 68218.0 45272.0 93154.0 1.36 2617.31 46414.0 387823.0 4.16 628.67
> stringtie-0-hisat-CONDITION_6-0.gtf.stats 48312.0 27943.0 68019.0 1.4 2469.96 28705.0 318795.0 4.69 527.0

- During `mikado prepare` 2 types of WARNINGS and 1 ERROR are logged

The "transcriptchecker.py:187 - WARNING - check_strand" appears 156 times
>2017-12-16 21:57:54,830 - Checker-14 - transcriptchecker.py:187 - WARNING - check_strand - Checker-14 - Transcript cuf-0-hst-CONDITION_5-0_CUFF.8738.1 has 2 positive and 1 negative splice junctions. Aborting.

The "transcript.py:965 - WARNING - reverse_strand" appears 32 times
>2017-12-16 21:57:10,871 - Checker-1 - transcript.py:965 - WARNING - reverse_strand - Checker-1 - Transcript cuf-0-hst-CONDITION_3-0_CUFF.6825.1 has been assigned to the wrong strand, reversing it.

This warning is triggered by the `suspicious_splicing` function with the following description:

`
"""This metric will return True if the transcript either has canonical introns
on both strands (probably a chimeric artifact between two neighbouring loci,
or if it has no canonical splicing event but it would if it were assigned to the opposite strand
(probably a strand misassignment on the part of the assembler/predictor)."""
`

Is it a problem inherited from assembly softwares ?

The "checking.py:91 - ERROR - create_transcript" appears 388 times:

> 2017-12-16 22:07:40,018 - Checker-13 - checking.py:91 - ERROR - create_transcript - Checker-13 -
> Traceback (most recent call last):
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
> transcript_object.check_strand()
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
> assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
> AssertionError

- No errors are triggered during prodigual step

- 2 ERRORS are triggered during `mikado pick` step

An error related to an invalid CDS length appears 869 times:

> 2017-12-17 02:53:02,373 - NW_011888782.1:16909755-16927209 - loci_processer.py:548 - ERROR - analyse_locus - LociProcesser-12 - Error while loading data for superlocus:NW_011888782.1mix
> ed:16909755-16927209
> 2017-12-17 02:53:02,374 - NW_011888782.1:16909755-16927209 - loci_processer.py:549 - ERROR - analyse_locus - LociProcesser-12 - (1409, 250, 1409, 'Invalid CDS length: 250 % 3 = 1', '#')
> Traceback (most recent call last):
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/picking/loci_processer.py", line 544, in analyse_locus
> data_dict=data_dict)
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 641, in load_all_transcript_data
> remove_flag, new_transcripts = self.load_transcript_data(tid, data_dict)
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 434, in load_transcript_data
> new_tr = list(self.transcripts[tid].split_by_cds())
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript.py", line 786, in split_by_cds
> for new_transcript in splitting.split_by_cds(self):
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 800, in split_by_cds
> new_transcripts = __create_splitted_transcripts(transcript, cds_boundaries)
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 536, in __create_splitted_transcripts
> new_bed12s = __relocate_orfs(transcript, bed12_objects, tstart, tend)
> File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 751, in __relocate_orfs
> str(new))
> AssertionError: (1409, 250, 1409, 'Invalid CDS length: 250 % 3 = 1', '#')

An error "loci_processer.py:457 - ERROR - remove_fragments" appears 8 times:

>2017-12-17 03:29:08,391 - NW_011892238.1:245-1482 - loci_processer.py:457 - ERROR - remove_fragments - LociProcesser-7 - Locus gene:NW_011892238.1+:365-1445 has been lost from superlocus NW_011892238.1:245-1482!

- Nethertheless at the end I got a result:

> File genes monoexonic_genes transcripts transcripts_per_gene transcript_len_mean monoexonic_transcripts exons exons_per_transcript exon_len_mean
> mikado-permissive.loci.stats 65701.0 37737.0 66544.0 1.01 1134.76 37737.0 203816.0 3.06 370.49

- I also used the test data ([daijin tutorial](http://mikado.readthedocs.io/en/latest/Tutorial/Daijin_tutorial.html)) to reproduce these errors/warnings by using data and parameters specified in the tutorial.

Only some errors have been reproduced:

The "transcriptchecker.py:187 - WARNING - check_strand" appears 4 times in prepare.log

> 2017-12-19 14:01:07,317 - Checker-1 - transcriptchecker.py:187 - WARNING - check_strand - Checker-1 - Transcript cls-0-hst-ERR1662534-0_X.1541.0 has 8 positive and 1 negative splice junctions.     Aborting.
> 2017-12-19 14:01:07,319 - Checker-8 - transcriptchecker.py:187 - WARNING - check_strand - Checker-8 - Transcript stn-0-hst-ERR1662534-0_Stringtie_0_hisat-ERR1662534-0.12694.1 has 8 positive and 1 negative splicejunctions.     Aborting.
> 2017-12-19 14:01:07,323 - Checker-16 - transcriptchecker.py:187 - WARNING - check_strand - Checker-16 - Transcript stn-0-hst-ERR1662533-0_Stringtie_0_hisat-ERR1662533-0.14660.1 has 5 positive and 1 negative splice junctions.     Aborting.
> 2017-12-19 14:01:07,348 - Checker-1 - transcriptchecker.py:187 - WARNING - check_strand - Checker-1 - Transcript cls-0-hst-ERR1662533-0_X.1597.0 has 3 positive and 1 negative splice junctions.     Aborting.

The error related to an invalid CDS length appears 3 times in mikado_pick.log:

> 2017-12-19 14:13:51,662 - 2R:14276134-14300106 - loci_processer.py:548 - ERROR - analyse_locus - LociProcesser-5 - Error while loading data for superlocus:2Rmixed:14276134-14300106
> 2017-12-19 14:13:51,663 - 2R:14276134-14300106 - loci_processer.py:549 - ERROR - analyse_locus - LociProcesser-5 - (701, 232, 701, 'Invalid CDS length: 232 % 3 = 1', '#')
> Traceback (most recent call last):
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/picking/loci_processer.py", line 544, in analyse_locus
>     data_dict=data_dict)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 641, in load_all_transcript_data
>     remove_flag, new_transcripts = self.load_transcript_data(tid, data_dict)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 434, in load_transcript_data
>     new_tr = list(self.transcripts[tid].split_by_cds())
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript.py", line 786, in split_by_cds
>     for new_transcript in splitting.split_by_cds(self):
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 800, in split_by_cds
>     new_transcripts = __create_splitted_transcripts(transcript, cds_boundaries)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 536, in __create_splitted_transcripts
>     new_bed12s = __relocate_orfs(transcript, bed12_objects, tstart, tend)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 751, in __relocate_orfs
>     str(new))
> AssertionError: (701, 232, 701, 'Invalid CDS length: 232 % 3 = 1', '#')

> 2017-12-19 14:14:18,553 - 3L:5922512-5932665 - loci_processer.py:548 - ERROR - analyse_locus - LociProcesser-16 - Error while loading data for superlocus:3Lmixed:5922512-5932665
> 2017-12-19 14:14:18,554 - 3L:5922512-5932665 - loci_processer.py:549 - ERROR - analyse_locus - LociProcesser-16 - (1600, 631, 1600, 'Invalid CDS length: 631 % 3 = 1', '#')
> Traceback (most recent call last):
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/picking/loci_processer.py", line 544, in analyse_locus
>     data_dict=data_dict)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 641, in load_all_transcript_data
>     remove_flag, new_transcripts = self.load_transcript_data(tid, data_dict)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 434, in load_transcript_data
>     new_tr = list(self.transcripts[tid].split_by_cds())
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript.py", line 786, in split_by_cds
>     for new_transcript in splitting.split_by_cds(self):
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 800, in split_by_cds
>     new_transcripts = __create_splitted_transcripts(transcript, cds_boundaries)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 536, in __create_splitted_transcripts
>     new_bed12s = __relocate_orfs(transcript, bed12_objects, tstart, tend)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 751, in __relocate_orfs
>     str(new))
> AssertionError: (1600, 631, 1600, 'Invalid CDS length: 631 % 3 = 1', '#')

> 2017-12-19 14:15:30,081 - X:1213802-1239683 - loci_processer.py:548 - ERROR - analyse_locus - LociProcesser-16 - Error while loading data for superlocus:Xmixed:1213802-1239683
> 2017-12-19 14:15:30,081 - X:1213802-1239683 - loci_processer.py:549 - ERROR - analyse_locus - LociProcesser-16 - (2548, 793, 2548, 'Invalid CDS length: 793 % 3 = 1', '#')
> Traceback (most recent call last):
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/picking/loci_processer.py", line 544, in analyse_locus
>     data_dict=data_dict)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 641, in load_all_transcript_data
>     remove_flag, new_transcripts = self.load_transcript_data(tid, data_dict)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/loci/superlocus.py", line 434, in load_transcript_data
>     new_tr = list(self.transcripts[tid].split_by_cds())
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript.py", line 786, in split_by_cds
>     for new_transcript in splitting.split_by_cds(self):
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 800, in split_by_cds
>     new_transcripts = __create_splitted_transcripts(transcript, cds_boundaries)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 536, in __create_splitted_transcripts
>     new_bed12s = __relocate_orfs(transcript, bed12_objects, tstart, tend)
>   File "/export/prog/python3/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/splitting.py", line 751, in __relocate_orfs
>     str(new))
> AssertionError: (2548, 793, 2548, 'Invalid CDS length: 793 % 3 = 1', '#')

- Precision:
  - gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
  - CLASS_v2.1.7
  - hisat2 version 2.1.0
  - stringtie 1.3.4
  - Prodigal V2.6.3: February, 2016
  - diamond version 0.9.14
  - Python 3.6.3

pip3 list output:

> appdirs (1.4.3)
> biopython (1.70)
> certifi (2017.11.5)
> chardet (3.0.4)
> ConfigArgParse (0.12.0)
> Cython (0.27.3)
> decorator (4.1.2)
> docutils (0.14)
> drmaa (0.7.8)
> frozendict (1.2)
> idna (2.6)
> intervaltree (2.1.0)
> jsonschema (2.6.0)
> Mikado (1.1)
> networkx (2.0)
> nose (1.3.7)
> numpy (1.13.3)
> pip (9.0.1)
> pyfaidx (0.5.1)
> python-magic (0.4.13)
> PyYAML (3.12)
> ratelimiter (1.2.0)
> requests (2.18.4)
> scikit-learn (0.19.1)
> scipy (1.0.0)
> setuptools (28.8.0)
> simplejson (3.13.2)
> six (1.11.0)
> snakemake (4.3.1)
> sortedcontainers (1.5.7)
> SQLAlchemy (1.1.15)
> SQLAlchemy-Utils (0.32.21)
> tabulate (0.8.1)
> ujson (1.35)
> urllib3 (1.22)
> wheel (0.30.0)
> wrapt (1.10.11)

I am using a SLURM scheduler with the --no_drmaa argument and the following conf : 

```
 __default__:
     threads: 16
     memory: 20000
     queue: all
 asm_trinitygg:
     memory: 20000
```

Mikado have been built using the git clone 71402f7266910fd553af248bf0920bf33774bd1f and the python3 setup.py test give the following output

> running test
> running egg_info
> writing Mikado.egg-info/PKG-INFO
> writing dependency_links to Mikado.egg-info/dependency_links.txt
> writing entry points to Mikado.egg-info/entry_points.txt
> writing requirements to Mikado.egg-info/requires.txt
> writing top-level names to Mikado.egg-info/top_level.txt
> reading manifest file 'Mikado.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '*' found under directory 'docs/'
> writing manifest file 'Mikado.egg-info/SOURCES.txt'
> running build_ext
> copying build/lib.linux-x86_64-3.6/Mikado/utilities/overlap.cpython-36m-x86_64-linux-gnu.so -> Mikado/utilities
> copying build/lib.linux-x86_64-3.6/Mikado/scales/f1.cpython-36m-x86_64-linux-gnu.so -> Mikado/scales
> copying build/lib.linux-x86_64-3.6/Mikado/scales/contrast.cpython-36m-x86_64-linux-gnu.so -> Mikado/scales
> copying build/lib.linux-x86_64-3.6/Mikado/utilities/intervaltree.cpython-36m-x86_64-linux-gnu.so -> Mikado/utilities
> Running unit tests for Mikado
> NumPy version 1.13.3
> NumPy relaxed strides checking option: True
> NumPy is installed in /export/prog/python3/lib/python3.6/site-packages/numpy
> Python version 3.6.3 (default, Nov 17 2017, 15:27:33) [GCC 4.8.4]
> nose version 1.3.7
> Warning: Can't read registry to find the necessary compiler setting
> Make sure that Python modules winreg, win32api or win32con are installed.
> .......................................................................................................................................................................................................................................................................................
> Ran 281 tests in 29.613s
>
> OK
> Traceback (most recent call last):
> File "setup.py", line 94, in <module>
> include_package_data=True
> File "/export/prog/python3/lib/python3.6/distutils/core.py", line 148, in setup
> dist.run_commands()
> File "/export/prog/python3/lib/python3.6/distutils/dist.py", line 955, in run_commands
> self.run_command(cmd)
> File "/export/prog/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "/export/prog/python3/lib/python3.6/site-packages/setuptools/command/test.py", line 210, in run
> self.run_tests()
> File "/export/prog/python3/lib/python3.6/site-packages/setuptools/command/test.py", line 231, in run_tests
> testRunner=self._resolve_as_ep(self.test_runner),
> File "/export/prog/python3/lib/python3.6/unittest/main.py", line 94, in __init__
> self.parseArgs(argv)
> File "/export/prog/python3/lib/python3.6/unittest/main.py", line 141, in parseArgs
> self.createTests()
> File "/export/prog/python3/lib/python3.6/unittest/main.py", line 148, in createTests
> self.module)
> File "/export/prog/python3/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
> suites = [self.loadTestsFromName(name, module) for name in names]
> File "/export/prog/python3/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
> suites = [self.loadTestsFromName(name, module) for name in names]
> File "/export/prog/python3/lib/python3.6/unittest/loader.py", line 211, in loadTestsFromName
> (obj, test))
> TypeError: calling <bound method NoseTester.test of <numpy.testing.nosetester.NoseTester object at 0x7fcdaf6962e8>> returned <nose.result.TextTestResult run=281 errors=0 failures=0>, not a test

- Are those errors already reported in other environment than mine ? Or do you think it could be related to my environment ?
- Does that mean that some locus have been ignored in the process ?

Thanks a lot

**Comment by lucventurini** [comment]
Dear jfouret,
                      thank you for your extremely detailed log. In order:

- WARNING - check_strand: this warning is expected and perfectly in order. During the prepare run, Mikado checks whether the splicing junctions of the transcript are coherent with the assigned strand. If they are not, Mikado will invert the strand. If there is a mixture of strands, like in your case, Mikado will refuse to analyse the transcripts. This is a quite common error among assemblers. 

- loci_processer.py: this is a subtle bug whose origin I have been unable to find, so far. It basically implies that some transcripts - that would have been categorised as fragments - have been discarded too soon by Mikado.

These two warnings can be safely ignored. They are there mostly for tracking reasons, and you might argue they should be at an INFO or DEBUG level. For the rest:

-  create_transcript: this is due to Mikado not finding a congruence between the lengths of the exons in the input file and the lengths of the FASTA sequence. It **might** be due to Mikado finding some models whose boundaries are outside the length of the scaffold, if you have a fragmented genome assembly, but I will have to investigate.

- InvalidCDS: from what I am seeing, the problem is that the ORFs that Prodigal finds internally seem not to be complete. Mikado checks that when there are internal ORFs of the transcript, the internal side of the ORF actually starts with a start codon, and that the CDS length is a multiple of three. In the cases shown above, this does not seem to be the case, hence the error. I will have to investigate when and why that seems to happen, so thank you for your bug report!

I do not think that the errors you report are due to your environment; for most software, I have tested with identical or similar versions to those present on your cluster.

I will investigate regarding the CDS issue and let you know.

Cheers

Luca

**Comment by lucventurini** [comment]
The "Warning" message for invalid strand has now been degraded to DEBUG.
