### ISSUE TITLE
Mikado serialize - not found in the index

### ISSUE THREAD

**Issue by ctxchris** [lucventurini/mikado#114]
Hi,

I'm getting a lot of warnings like this:

> serialiser - orf.py:281 - WARNING - serialize - MainProcess - Invalid entry, reason: STRG.1000.1 not found in the index!
STRG.1000.1	0	3083	ID=STRG.1000.1.p1;GENE.STRG.1000.1~~STRG.1000.1.p1;ORF_type:5prime_partial_len:540_(+),score=167.57	0	+	2	1622	0	1	3083	0

The respective entry stems from a stringtie assembly. I provided the stringtie gtf at the configure stage where the entry is represented like this:

> Scaffold_2	StringTie	transcript	13562237	13569531	1000	+	.	gene_id "STRG.1000"; transcript_id "STRG.1000.1"; cov "476.308655"; FPKM "9.781632"; TPM "16.612072";
Scaffold_2	StringTie	exon	13562237	13562368	1000	+	.	gene_id "STRG.1000"; transcript_id "STRG.1000.1"; exon_number "1"; cov "285.452942";
Scaffold_2	StringTie	exon	13563154	13563227	1000	+	.	gene_id "STRG.1000"; transcript_id "STRG.1000.1"; exon_number "2"; cov "704.302124";
Scaffold_2	StringTie	exon	13563668	13563860	1000	+	.	gene_id "STRG.1000"; transcript_id "STRG.1000.1"; exon_number "3"; cov "773.906677";

At the serialise stage, I provided the stringtie TransDecoder Bed file where the "STRG.1000.1" is found in this line:
> STRG.1000.1	0	3083	ID=STRG.1000.1.p1;GENE.STRG.1000.1~~STRG.1000.1.p1;ORF_type:5prime_partial_len:540_(+),score=167.57	0	+	2	1622	0	1	3083	0

Is there something wrong with the formatting of the files?

I also noticed an error in the GTF parser module at column 70 when there is a ";" in the reference fasta header.

Thanks,
Chris

**Comment by lucventurini** [comment]
Dear Christian,
                           Have you provided the cDNA FASTA file to serialise? Off the top of my head, that's the most likely cause for the error.
It might help if you could provide the command lines you are using.

Kind regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctxchris** [comment]
Hi Luca,

I ran the following commands:

`mikado configure --list mikado.list --reference ref.fasta  --junctions portcullis_filtered.pass.junctions.reheader.bed --mode permissive -t 50 -od ./ --intron-range 20 500000 configuration.yaml`

`mikado prepare -scds --json-conf configuration.yaml -p 50`

`diamond blastx --max-target-seqs 5 --threads 40 --query mikado_prepared.fasta --outfmt 5 --db /databases/UniProt/swissprot/uniprot_sprot  --evalue 0.000001 2> blast.log | sed '/^$/d' | gzip -c - > mikado.blast.xml.gz`

`mikado serialise --json-conf configuration.yaml --xml mikado.blast.xml.gz --blast_targets /databases/UniProt/swissprot/uniprot_sprot.fasta --orfs stringtie_transcripts.transdecoder.bed,cufflinks_transcripts.transdecoder.bed -p 50`

Content of mikado.list:

> cufflinks.gtf	cl	True	1
class2.gtf	cla	True
stringtie.gtf	st	True	1
reference.cds.gff3	ref	False
Trinity-GG.gff3	trg	False

The warning also occurs for the cufflinks entries.

Thanks,
Chris

**Comment by lucventurini** [comment]
Hi Christian,
                      The problem is that Mikado serialise is missing the input transcripts. If you update the CL to:


mikado serialise --json-conf configuration.yaml --xml mikado.blast.xml.gz --blast_targets /databases/UniProt/swissprot/uniprot_sprot.fasta --orfs stringtie_transcripts.transdecoder.bed,cufflinks_transcripts.transdecoder.bed -p 50 -–transcripts mikado_prepared.fasta

You should see the error messages disappear. I will revise the documentation to make the point clearer!

Please let me know if the proposed solution fixes your issue.

Kind regards

Luca Venturini, PhD
Computational Biologist

[cid:image002.png@01D1CE42.9C13ED10]
Earlham Institute
Norwich Research Park
Norwich
Norfolk
NR4 7UZ
+44 1603 450 190
Luca.Venturini@earlham.ac.uk<mailto:Luca.Venturini@earlham.ac.uk>
www.earlham.ac.uk<http://www.earlham.ac.uk/>

**Comment by ctxchris** [comment]
Hi Luca,

I realized my mistake this morning and run it again with the `--transcripts mikado_prepared.fasta` option, but the error stays the same. I find the "invalid entry" STRG.1000.1  as well in the fasta file as in the index:

>grep "STRG.1000.1" mikado_prepared.fasta
 st_STRG.1000.1`

>grep "STRG.1000.1" mikado_prepared.fasta.fai 
st_STRG.1000.1	3083	95488188	60	61

I just noticed a difference between TansDecoder v5.0.1 and v5.0.2 output which might be a reason why the bed parser has difficulties.
v5.0.1:
>ID=Gene.1920::CUFF.1.1::g.1920::m.1920;Gene.1920::CUFF.1.1::g.1920;ORF_type:5prime_partial_len:107_(+),score=15.50

v5.0.2:
>ID=STRG.1000.1.p1;GENE.STRG.1000.1~~STRG.1000.1.p1;ORF_type:5prime_partial_len:540_(+),score=167.57

Running serialise without the ORF files didn't produce any error so far. I'll run TransDecoder v5.0.1 
on the gtf files and try again with the new bed files.

Thanks,
Chris

**Comment by lucventurini** [comment]
Hi Christian,
                      If the only difference between the two BED files is the presence of the “~” signs, I do not believe that that would cause the error. Mikado should use the first field in the BED file (the “chromosome”) to determine the ID to look for in the index, not the name.
If indeed TD 5.0.1 functions but 5.0.2 does not, that is an issue I will have to tackle ASAP, so thank you for the heads up.
Did you delete the mikado.db file before re-running Mikado serialise? I am just wondering whether a partially corrupt database might generate the issues that you are seeing.

Kind regards

Luca Venturini, PhD
Computational Biologist

[cid:image002.png@01D1CE42.9C13ED10]
Earlham Institute
Norwich Research Park
Norwich
Norfolk
NR4 7UZ
+44 1603 450 190
Luca.Venturini@earlham.ac.uk<mailto:Luca.Venturini@earlham.ac.uk>
www.earlham.ac.uk<http://www.earlham.ac.uk/>

**Comment by ctxchris** [comment]
Hi Luca,

you're right, running serialise it with the old TransDecoder format resulted in the same error.
I always deleted the output of a stage when I run it again.
Despite the those warnings, all stages run through and produce a gff in the end. However, the entries contain only non-coding genes:

>count type  
118892 exon
  26241 ncRNA
  21625 ncRNA_gene
  21099 superlocus

The gff without using the ORF evidence also only contained nrRNA genes.

The prepare log file only contains a couple of the following warnings:

>Checker-25 - transcriptchecker.py:187 - WARNING - check_strand - Checker-25 - Transcript cl_CUFF.44327.1 has 13 positive and 1 negative splice junctions.     Aborting.
Checker-9 - transcriptchecker.py:187 - WARNING - check_strand - Checker-9 - Transcript cl_CUFF.24510.3 has 9 positive and 1 negative splice junctions.     Aborting.
prepare - prepare.py:447 - INFO - prepare - MainProcess - Finished

Could there be something wrong with the TransDecoder files? Do you have a small test set, that I could check for the correct formatting?

Thanks,
Chris

**Comment by lucventurini** [comment]
Hi Christian,
                    I just realized where the problem lies ... Mikado serialise presumes that the IDs in the GTF (mikado_prepared.gtf) are the same as those used for TransDecoder. However, from what I understand you ran TransDecoder on the assemblies *before* running mikado prepare. The problem is that Mikado prepare, to avoid ID collisions when merging multiple files, prefixes all IDs with a sample-specific string.

For example, if you look, the stringtie models in the mikado_prepare.gtf file have all a "st_" prefix. As you have run TransDecoder on the Stringtie output directly, though, the "st_" prefix is absent. Mikado serialise is therefore unable to make the connection between the TD ORF and the mikado_prepared ID.

The fastest solution but not recommended is to use sed to add the assembly-specific tag to the TransDecoder BEDs (e.g. sed -i 's/^/st_/' stringtie_transcripts.transdecoder.bed). The recommended but slower solution is to run TransDecoder on the mikado_prepared.fasta file.

I will definitely update the documentation to make this point clear, so thank you for showing me places where it lacks clarity.

Please let me know if the proposed solution(s) function.

Kind regards

Luca Venturini

**Comment by ctxchris** [comment]
Hi Luca,

this did the trick, thanks!
Maybe you have a recommendation concerning parameters:

The final gene structure has a considerably smaller gene- and mRNA length (1/3 - 1/2) compared to the input data. The gene coordinates between the input files have high agreement though. I'm wondering why that is and if I could change the behavior by altering some parameters.

Thanks,
Christian

**Comment by lucventurini** [comment]
Hi Christian,
                   sorry for the late reply. Could you explain a bit better what is the issue with the Mikado models - is it that the models are shorter, on average, than the input transcripts?
If that is the case, it is most probably the case that Mikado detected many chimeric transcripts and split them according to the ORF data. You should be able to tell whether that is the case by looking at the alias field in the GFF: if the alias has a "split" suffix, that is what happened. You can find more details in the  [documentation](http://mikado.readthedocs.io/en/latest/Algorithms.html?highlight=chimera) and in our [preprint](https://www.biorxiv.org/content/early/2017/12/21/216994). I would *not* recommend turning this feature off, as these chimeras are artefacts which will degrade the quality of your final annotation. You can however tweak the behaviour through the [configuration file](http://mikado.readthedocs.io/en/latest/Usage/Configure.html#chimera-splitting).

Best
Luca
