### ISSUE TITLE
Creating the `trinity.gff3` file

### ISSUE THREAD

**Issue by martinjvickers** [lucventurini/mikado#118]
Hi Luca,

I'm attempting to follow your [tutorial](https://mikado.readthedocs.io/en/latest/Tutorial/index.html) with some of our own data and I'm a little unsure how to create the `trinity.gff3` file. In the docs it says;

> trinity.gff3: a GFF3 file of transcripts assembled using Trinity and aligned using GMAP

Am I correct in thinking that I need to map the assembled transcriptome (the `Trinity.fasta` file) to the reference genome (in my case TAIR10) to create the `trinity.gff3` file?

Do you happen to have the commands/parameters/scripts that were used to create the `sample_data` files. It would be helpful to be able to understand how to apply your pipeline to our own data.

Many thanks,

Martin

**Comment by lucventurini** [comment]
Dear Martin and Yi,
                                the trinity.gff3 file cited in the tutorial is present in the sample_data directory (https://github.com/lucventurini/mikado/blob/master/sample_data/). Details on how the assemblies were generated, including of how the Trinity transcripts were aligned onto the genome with GMAP, can be found in the manuscript: https://www.biorxiv.org/content/biorxiv/early/2017/12/21/216994.full.pdf

In general we recommend to use the Daijin pipeline (see Tutorial: https://mikado.readthedocs.io/en/latest/Tutorial/Daijin_tutorial.html) to drive the alignments and assemblies of reads. This will take care as well of aligning the Trinity transcripts with GMAP. It is the pipeline that was used to generate the data for the paper, including the small sample present for testing and training purposes in sample_data.

Kind regards

Luca

**Comment by yifangt** [comment]
Thanks a lot!

Yifang

**Comment by martinjvickers** [comment]
Thank you. Maybe the daijin tutorial should be where the "quick start" links to?
