### ISSUE TITLE
DRMAA_LIBRARY_PATH when running locally

### ISSUE THREAD

**Issue by martinjvickers** [lucventurini/mikado#119]
I've installed mikado with bioconda locally along with the dependencies required.

I'm getting the following error;

```
[mvickers@x250 daijin]$ daijin configure --scoring plants.yaml --copy-scoring plants.yaml -m permissive --sample-sheet samplesheet.tsv --flank 500 -i 50 26000 --genome TAIR10_reference_wCM.fa -al hisat -as class stringtie -od TAIR10 -o daijin.yaml --name TAIR10 --prot-db uniprot_sprot_plants.fasta
[mvickers@x250 daijin]$ daijin assemble --cores 1 daijin.yaml
wildcard constraints in inputs are ignored
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/miniconda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/snakemake/executors.py", line 853, in _wait_for_jobs
    import drmaa
  File "/usr/local/miniconda/lib/python3.6/site-packages/drmaa/__init__.py", line 65, in <module>
    from .session import JobInfo, JobTemplate, Session
  File "/usr/local/miniconda/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
    from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
  File "/usr/local/miniconda/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
    from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
  File "/usr/local/miniconda/lib/python3.6/site-packages/drmaa/wrappers.py", line 54, in <module>
    '{0}').format(_drmaa_lib_env_name))
RuntimeError: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH

WorkflowError:
Error loading drmaa support:
Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
```

I'm not attempting to use a scheduler so no DRMAA libraries are installed locally. Do I need to go about installing SGE/SLURM or something locally to run this software?

**Comment by lucventurini** [comment]
Dear @martinjvickers ,
                                   the command:
``daijin assemble -nd --cores 1 daijin.yaml``

should function. Please note the "-nd", which instructs Daijin *not* to make use of DRMAA.
If it does not, please let me know so that I can look into the issue in more detail.

I will try to make Daijin more clever by switching to no DRMAA if none is found, but it might not be straight-forward as the error is triggered in the Snakemake library rather than our own program.

Kind regards

Luca Venturini

**Comment by martinjvickers** [comment]
Hi @lucventurini, 

Perfect, thank you. Maybe the `-nd` flag should be added to the Daijin [tutorial](https://mikado.readthedocs.io/en/latest/Tutorial/Daijin_tutorial.html#step-2-running-the-assemble-part). My assumption was that by not specifying a `--scheduler` that we were in local mode.

As a quick aside, even if you fix the reported error by installing a DRMAA library, you get crazy errors coming from snakemake that make little sense to the Daijin user. 

Cheers,

Martin

**Comment by lucventurini** [comment]
Hi Martin,
                I am releasing version 1.2.2 which should fix the problem permanently.
Cheers,

Luca

**Comment by martinjvickers** [comment]
Great thank you
