### ISSUE TITLE
Ability to handle multiple BLASTX alignment files

### ISSUE THREAD

**Issue by maplesond** [lucventurini/mikado#48]
Potentially, users might want to align transcripts against multiple protein databases and feed that information into mikado serialise.  It might be nice to have a way of handling this in mikado. As an alternative workaround we could make it clear in the documentation that one way to handle this scenario is to concatenate the protein fasta files together before creating the BLAST database.

**Comment by lucventurini** [comment]
Solved in Daijin by merging together the FASTA files. Closing.
