### ISSUE TITLE
[Daijin] Allow Daijin to use single-end Illumina datasets

### ISSUE THREAD

**Issue by lucventurini** [lucventurini/mikado#91]
At the moment Daijin only accepts paired-end samples, which could be an unduly burden for some projects. We should provide a way of supplying and using single-end datasets as well.

**Comment by martinjvickers** [comment]
@lucventurini I've just noticed this issue. This isn't still a problem is it? It's not mentioned anywhere in your docs or paper and it's an old issue. The tutorial even goes as far as saying in the [docs](https://mikado.readthedocs.io/en/latest/Tutorial/Daijin_tutorial.html#step-1-configuring-daijin) describing the Daijin samplesheet that;

> - Read2: optional, location of the right reads for the sample if it is paired.

**Comment by lucventurini** [comment]
Hi Martin,
                 this should indeed not be a problem any longer. We solved this a long time ago, I just forgot to close the issue.
I am testing it now on a small dataset and I will let you know soon.
Incidentally, thank you for preparing the singularity recipe. I will review it soon!

Kind regards
