### ISSUE TITLE
[Daijin] Allow for Diamond instead of BLASTX

### ISSUE THREAD

**Issue by lucventurini** [lucventurini/mikado#93]
I just had a look at DIAMOND again. They added some time ago the capability of obtaining XML output instead of only tabular. I have to say I am **hugely** impressed ... it was able to perform the alignment of ~20,000 sequences in less than three minutes for my Mikado run.

Given the purpose for which we use BLAST (ie finding chimeras), we do not need super-accurate results. Giving the users the chance of using Diamond instead of BLASTX might cut down the processing time massively, leaving TransDecoder as the only choke point of the pipeline.

**Comment by lucventurini** [comment]
Update - now Daijin supports DIAMOND. Caveats:

- DIAMOND will support proper XML files that Mikado can use, but only from the *next* release. I had to signal and correct a couple of small bugs in the XML output.
- I am not able to make Snakemake choose dynamically between BLASTX and DIAMOND. This causes quite an inflexibility in the program.

**Comment by maplesond** [comment]
Cool.  I found results to be very different between BLAST and diamond last year but agree the runtime is attractive.  If diamond is behaving sufficiently well for mikado then this is great.  I think dynamic selection might be tricky due to controlling all the additional options.  It's best to leave this in the users hands.

**Comment by lucventurini** [comment]
I have to verify that last bit about the results (yesterday I was just trying to make it work, period). The problem I have at the moment is that I have no way of choosing at runtime which tool to use. There is the ``ruleorder:`` key in snakemake file, but it is unclear how one can modify it dynamically.

**Comment by lucventurini** [comment]
This mail exchange seems to suggest that it should be possible to obtain the desired behaviour with an if-else statement and a boolean variable in the configuration dictionary. This would be great!

https://groups.google.com/forum/#!searchin/snakemake/ambiguous%7Csort:relevance/snakemake/qX7RfXDTDe4/rfsF3UrQAAAJ

**Comment by lucventurini** [comment]
If-else behaviour implemented, and accessible through a not-advertised-for option in the configuration file. Closing for now, at least until Diamond solves its own output problems.
